spring:
  application:
    name: cv
  datasource:
    url: jdbc:sqlserver://158.23.246.23:1433;database=microserviciosPT;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: sa
    password: 'Ipn2024!'
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      properties:
        hibernate.format_sql: true
logging:
  file:
    name: ./logs/cvms-${date:yyyy-MM-dd}.log # Archivo con fecha en el nombre
server:
  port: 8082
eureka:
  instance:
    ip-address: 158.23.81.1
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://158.23.81.1:8761/eureka
jwt:
  secret: 357638792F423F4421472B4B6250655368566D597133743677397A2443264629

#http://host.docker.internal:8761/eureka
#jdbc:sqlserver://pt-server1.database.windows.net:1433;database=usersms;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net